---
name: CI-system

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  t:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: t
        run: |
          make test_container
  t-system:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: t
        run: |
          make test_system
